version: "3.8"

services:
  frontend:
    build:
      context: ./havenly_frontend-main
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3001

  backend:
    build:
      context: ./havenly_backend-main
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./havenly_backend-main:/app
      - /app/node_modules
    restart: unless-stopped
