version: "3.8"

services:
  frontend:
    image: ${FRONTEND_IMAGE}:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:3001

  backend:
    image: ${BACKEND_IMAGE}:latest
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./havenly_backend-main/uploads:/app/public/uploads
    restart: unless-stopped
