version: "3.8"

services:
  frontend:
    build:
      context: ./havenly_frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:3001

  backend:
    build:
      context: ./havenly_backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./havenly_backend/havenly_backend:/app
      - /app/node_modules
    restart: unless-stopped
