version: "3.8"

services:
  backend:
    build: ./havenly_backend-main
    ports:
      - "3001:3001"
    # environment:
    #   - NODE_ENV=production
    # volumes:
    #   - ./havenly_backend:/app
    #   - /app/node_modules
    depends_on:
      - mongo

  frontend:
    build: ./havenly_frontend-main
    ports:
      - "5173:5173"
    # environment:
    #   - NODE_ENV=production
    # volumes:
    #   - ./havenlyfrontend:/app
    #   - /app/node_modules
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
